---

- name: Creating users from external file
  hosts: webservers
  become: true

  vars_files:
  - users.yml

  tasks:
  - name: Creating user
    user:
      name: "{{item}}"
      state: present
    with_items:
    - "{{username}}"
    - "{{username2}}"
    - "{{username3}}"
    - "{{username4}}"

  

