##Installing Tomcat Application Server

---

- name: Installing Tomcat on webservers
  hosts: webservers
  become: true

  tasks:
  - name: Installing Java on RedHat nodes
    yum: 
     name: java
     state: installed
    when: ansible_os_family == "RedHat"
  - name: Installing Java on Debian  nodes
    apt:
     name: default-jdk
     state: present
    when: ansible_os_family == "Debian"
  - name: Download Tomcat package
    get_url:
     url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.70/bin/apache-tomcat-8.5.70.tar.gz
     dest: /opt/
  - name: unzip tomcat package
    unarchive: 
     src: /opt/apache-tomcat-8.5.70.tar.gz
     dest: /opt/
     remote_src: true
  - name: Giving permission to statup.sh file
    file: 
     path: /opt/apache-tomcat-8.5.70/startup.sh
     mode: 0777
     recurse: true
  - name: Start Tomcat server
    shell: nohup ./startup.sh
    args:
     chdir: /opt/apache-tomcat-8.5.70/bin/

