---
- name: Webserver Creation
  hosts: all
  become: yes
  tasks:
   - name: Installing httpd
     yum:
      name: httpddddddddd
      state: installed
     ignore_errors: yes
   - name: Copy Index.html file
     copy:
      src: index.html
      dest: /var/www/html
   - name: Starting httpd service
     service:
      name: httpd
      state: started
      enabled: yes
